# This workflow triggers when creating a new release.
# It updates the 'version'-tag in the config.yaml and then pushes a new commit to the repo and
# updates the release tag.

name: Release

on:
  release:
    types: [published]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      # TODO: instead of failing, change the tags name
      - name: fail on invalid version
        run: |
          if [[ $GITHUB_REF_NAME != v* ]]
          then
            exit 1
          fi

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: set version number
        id: version
        run: echo "num=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: edit config file
        run: sed -i "s/^version:.*$/version:\ ${{ steps.version.outputs.num }}/" config.yaml

      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "🤖 bump version" -m "Changed version in config to ${{ steps.version.outputs.num }}"

      - name: push to main
        run: |
          git push origin main

      - name: update release tag
        run: |
          git tag --force -a "${GITHUB_REF_NAME}" -m "Release ${GITHUB_REF_NAME}"
          git push --force origin "${GITHUB_REF_NAME}"
